name: Run Postman Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Set the Node.js version to 20

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman collection
      run: newman run ./my-postman-collection.json  # Ensure this path is correct
